version: "2"
services:
  web:
    # 使用你自己的username/repo:tag
    image: registry.cn-hangzhou.aliyuncs.com/xuyuanjia/webservers:v1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "1"
          memory: 512M
      restart_policy:
        condition: on-failure
    ports:
    - "8888:8080"
    networks:
    - bridge
networks:
  bridge: